import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar"
import ContactDock from "@/components/wptel/ContactDock";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        {children}

        <ContactDock
          whatsapp={{ number: "905555555555", message: "Merhaba, bilgi almak istiyorum." }}
          phone={{ number: "+905555555555", label: "Hızlı İletişim" }}
          position="br" // "bl" | "tr" | "tl"
        />
      </body>
    </html>
  );
}
